### ISSUE TITLE
Uploading resources

### ISSUE THREAD

**Issue by psengelke** [MaretStoffberg/COS301_phase3_ResourcesA#4]
Issues:
  * The **uploadFile** function's signature needs to be changed to **uploadResources(files, callback)**.
  * The **checkMimeType** function still needs to be properly implemented. (I'm not sure who was in charge of that but another issue will be opened describing the details so you can use it properly).
  * Lines 57 - 63 (```resources.getConstraints(function(err, results){...}```) are redundant since **checkMimeType** will be changed.

Notes on callbacks and returning from functions:
  * Callback functions provide a mechanism for supplying the caller with a "return value" from an asynchronous method, but are not themselves returned.
  * To return from the function prematurely, simply say ```return;``` after you call the callback function.

**Comment by patiencemtsweni** [comment]
ok. will have a look at those issues and fix them
